name: Executar ZIP

on:
  push:
    branches: [ "main" ] # Executa toda vez que você atualizar o repositório
  workflow_dispatch:      # Permite executar manualmente com um clique

jobs:
  rodar-codigo:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    - name: Descompactar o arquivo ZIP
      run: unzip codigo.zip -d pasta_extraida

    - name: Executar o arquivo
      run: |
        cd pasta_extraida
        python script.py # Substitua pelo comando do seu script (ex: node index.js)
